### ISSUE TITLE
Check Information leakage

### ISSUE THREAD

**Issue by wangz3066** [CongWeilin/GraphMixer#1]
Hi authors, 
I am looking at this code and wondering whether there may be information leakage problem. 
I think the core neighbor sampling code is: 
https://github.com/CongWeilin/GraphMixer/blob/bbdd9923706a02d0619dfd00ef7880911f003a65/sampler_core.cpp#L295-L319
where nts is the current timestamp and ts[e_serach] is the latest timestamp of neighbor. 
I debug this two variables and find that ts[e_search] is not strictly smaller than nts, i.e., the sampled neighbor maybe from future. 
Then i look back on the TGAT style binary search code: 
https://github.com/CongWeilin/GraphMixer/blob/bbdd9923706a02d0619dfd00ef7880911f003a65/sampler_core.cpp#L273-L277
e_search is obtained by std::upper_bound, and i check the cpp document about this function (https://cplusplus.com/reference/algorithm/upper_bound/): 
std::upper bound Returns an iterator pointing to the first element in the range [first,last) which compares greater than val.
Therefore, ts[e_serach] greater than n_ts, which causes information leakage. 
I am wondering whether I am right.

**Comment by CongWeilin** [comment]
Hi, thank you for being interested in our work.

I think your question is related to https://github.com/amazon-science/tgl/issues/7#issue-1262489648. I am using the sampler provided by this repository. 

Besides, I have implemented a function to go through all training data to check information leakage, please refer to https://github.com/CongWeilin/GraphMixer#comments. This function will check if neighbor nodes' edges have eid smaller than the eid of the link we want to predict, where in the raw data older edges always have smaller eid.

**Comment by wangz3066** [comment]
Thanks for your reply! But I wonder why this implementation of JODIE, TGAT, TGN perform so well on MOOC dataset?

**Comment by wangz3066** [comment]
Thanks for your reply!
