### ISSUE TITLE
Changing number of negative samples 

### ISSUE THREAD

**Issue by muberraozmen** [CongWeilin/GraphMixer#2]
Hi congrats for the excellent work!

Trying to experiment with the number of negative samples greater than 1 (e.g. 3), getting `ValueError: operands could not be broadcast together with shapes (1800,) (600,)` error from `get_random_inds` function in `data_process_utils.py`.

Do you happen to recognize the issue and have a quick fix?

**Comment by CongWeilin** [comment]
Hi, could you please paste the full error message you got?

**Comment by muberraozmen** [comment]
He it is:
>>> Epoch  1
train mode with negative samples 3 ...:   0%|                                                                                             | 0/184 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/research-repo/muberra-MrTGL/baselines/GraphMixer/train.py", line 244, in <module>
    model = link_pred_train(model.to(args.device), args, g, df, node_feats, edge_feats)
  File "/home/research-repo/muberra-MrTGL/baselines/GraphMixer/link_pred_train_utils.py", line 164, in link_pred_train
    train_ap, train_auc, train_f1, train_loss = run(model, optimizer, args, train_subgraphs, df,
  File "/home/research-repo/muberra-MrTGL/baselines/GraphMixer/link_pred_train_utils.py", line 66, in run
    mini_batch_inds = get_random_inds(len(subgraph_data_list), cached_neg_samples, neg_samples)
  File "/home/research-repo/muberra-MrTGL/baselines/GraphMixer/data_process_utils.py", line 154, in get_random_inds
    neg_dst_inds = batch_size * neg_dst_inds + np.arange(batch_size)
ValueError: operands could not be broadcast together with shapes (1800,) (600,)
train mode with negative samples 3 ...:   0%|                                                                                             | 0/184 [00:01<?, ?it/s]

**Comment by CongWeilin** [comment]
Hi, I think you might need to delete the previously cached graph, otherwise https://github.com/CongWeilin/GraphMixer/blob/bbdd9923706a02d0619dfd00ef7880911f003a65/link_pred_train_utils.py#L59 will load the previously cached graph, which is just 600 elements.

Sorry for the late reply. I currently don't have access to my machine and I couldn't debug it myself ... but I recall that I have previous test more than one negative samples, it should work fine.

**Comment by muberraozmen** [comment]
Yes thank you!
